### ISSUE TITLE
sendWithParam方法的sign参数传空字符串报错

### ISSUE THREAD

**Issue by jzhouw** [qcloudsms/qcloudsms_csharp#2]
result信息："{\"result\":1014,\"errmsg\":\"package format error, sdkappid not have this tpl_id\",\"ext\":\"\"}"

**Comment by qcloudsms** [comment]
您好，这个是模板参数问题

**Comment by jzhouw** [comment]
那么是怎么解决的？为什么关掉这个issue?

**Comment by qcloudsms** [comment]
@jamesatgithub 您好，这个应该您模板参数没有传对导致的，您可以找咨询腾讯云短信技术支持(QQ:3012203387)帮忙一起解决。
